theme: jekyll-theme-minimal
title: Estado de proyectos y noticias
logo: https://github.com/utvoluntariado/utv-graphic-resources/raw/main/png/logo%20%2B%20name/light%20mode/UTV%20Logo%20%2B%20name%40746x172.png
show_downloads: false
