theme: jekyll-theme-minimal
title: Noticias de la UTV
description: Noticias y estado de proyectos de la Unidad Tecnológica de Voluntariado
logo: https://github.com/utvoluntariado/utv-graphic-resources/raw/main/png/logo%20%2B%20name/light%20mode/UTV%20Logo%20%2B%20name%40746x172.png
show_downloads: false
